---
title: "ESOC 2024: Small vessel disease burden in acute ischemic stroke - the role of physical activity and vascular risk factors"
date: 2024-04-30
execute: 
  freeze: true
description: I will be sharing the challenge of assessing 1055 acute stroke patients scans and the analysis work to investigate the interaction between physical activity and classical cardio-vascular risk factors and the effect on SVD burden.
categories:
  - Conference abstract
  - Physical activity
  - Stroke
  - Small vessel disease
  - SVD
  - Poster
  - R
bibliography: references.bib
---

## Intro

For this years ESOC event, I have been preparing a poster on my last PhD-project. In this project we are aiming to investigate the relation between physical activity (PA), small vessel disease (SVD) and classical cardiovascular risk factors such as hypertension, diabetes and smoking.

## Data and SVD assessment

For this project, data has been pooled from two large clinical trials.[@kraglund2018; @blauenfeldt2023] Available MR-scans were assessed with the help of 7 trained clinicians. The process is documented including the REDCap assessment tool in [this repository](https://agdamsbo.github.io/cSVD-burden-annotation-and-analysis-project/). I had planned to only allocate one assessor to each subject, but after an initial batch of 50 subject, assessed by all assessors, two assessors were allocated for each subject. Also, it was decided to have all assessments with disagreement evaluated by a third assessor for a consensus score. This work is still under-way (as of 13. May 2024).

Data analysis and further work is [documented in another repository](https://agdamsbo.github.io/svd-modification/), which was also intended for poster generation with [quarto](https://quarto.org/docs/output-formats/typst-custom.html). I did not like the text-heavy templates and did not have the time to start creating my own, so I ended up using Microsoft's PowerPoint, which is great for the task. This is the result.

## Further work

This study is part of a bigger project on exploring which SVD parameters can be extracted from acute stroke scans, which is available in this large cohort. This work is continuing and will hopefully lead to new interesting insights as to pragmatic SVD evaluation in stroke patients.
