project:
  type: website
  output-dir: docs

resources:
  - CNAME
# https://github.com/quarto-dev/quarto-cli/discussions/3249

website:
  title: "Andreas"
  favicon: "/images/favicon.png"
  site-url: https://andreas.gdamsbo.dk
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: academia.qmd
        text: Research
      - href: health-data.qmd
        text: Other projects
      # - about.qmd
    right: 
      - href: https://github.com/agdamsbo/andreas.gdamsbo
        text: Source
  page-footer: 
    background: light
    center: "Made using [Quarto](https://quarto.org/), Copyright 2023, Andreas Gammelgaard Damsbo. Statistics with [Umami](https://stats.nikohuru.dk/share/bG56ngAz4o7dVeD1/andreas.gdamsbo) on private server."
  # cookie-consent:
  #   type: express
  #   style: headline
  #   palette: light
  #   prefs-text: "This page uses an extremely minimal tracking tool (Umami) hosted on a private server. No data is shared with any third-party."

format:
  html:
    theme: solar
    # css: styles.css
    toc: true
    link-external-newwindow: true
    includes:
      in_header: header.html

editor: visual

