project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

resources:
  - CNAME
# https://github.com/quarto-dev/quarto-cli/discussions/3249

website:
  title: "Damsbo AG"
  favicon: "/images/favicon.png"
  site-url: https://andreas.gdamsbo.dk
  repo-url: https://github.com/agdamsbo/andreas.gdamsbo
  repo-actions: [source, issue]
  page-navigation: true
  comments:
    hypothesis: 
      theme: clean
  search:
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: academia.qmd
        text: Research
      - href: health-data.qmd
        text: Health data projects
      - href: mixed.qmd
        text: Other projects
      # - about.qmd
    right:
      - href: https://github.com/agdamsbo/andreas.gdamsbo
        text: Source
  page-footer: 
    background: dark
    center: |
      Made using [Quarto](https://quarto.org/) | [CC BY-NC 4.0](LICENSE.html) | Statistics with [Umami](https://analytics.gdamsbo.dk/share/TLJEY9tJaZ324zTH/Andreas) | [Contact](mailto:andreas@gdamsbo.dk)

format:
  html:
    code-fold: true
    code-overflow: wrap
    theme: 
      light: lumen
      dark: solar
    # css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    include-in-header: umami.html
    email-obfuscation: references

editor: visual

